/**
 * Prisma configuration file that specifies the schema location, migrations path,
 * and MongoDB datasource URL loaded from environment variables.
 */

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["MONGODB_URI"],
  },
});
